"""initial_schema

Revision ID: 63989ac54a23
Revises: 
Create Date: 2026-07-17 06:28:24.931545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63989ac54a23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_tool_call_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correlation_id', sa.String(length=255), nullable=False),
    sa.Column('tool_name', sa.String(length=255), nullable=False),
    sa.Column('server_name', sa.String(length=255), nullable=False),
    sa.Column('arguments', sa.Text(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tool_call_audits_correlation_id'), 'mcp_tool_call_audits', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_call_audits_server_name'), 'mcp_tool_call_audits', ['server_name'], unique=False)
    op.create_index(op.f('ix_mcp_tool_call_audits_tool_name'), 'mcp_tool_call_audits', ['tool_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workflow_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('input_query', sa.Text(), nullable=False),
    sa.Column('current_step', sa.String(length=128), nullable=False),
    sa.Column('current_status', sa.String(length=64), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('retrieval_results', sa.JSON(), nullable=True),
    sa.Column('agent_finding', sa.Text(), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('error_info', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('total_tokens_used', sa.Integer(), nullable=False),
    sa.Column('token_budget', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('cost_budget_usd', sa.Float(), nullable=False),
    sa.Column('is_human_review_needed', sa.Boolean(), nullable=False),
    sa.Column('human_decision', sa.String(length=32), nullable=True),
    sa.Column('human_comment', sa.Text(), nullable=True),
    sa.Column('review_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_current_status'), 'workflow_runs', ['current_status'], unique=False)
    op.create_index(op.f('ix_workflow_runs_session_id'), 'workflow_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_user_id'), 'workflow_runs', ['user_id'], unique=False)
    op.create_table('human_review_decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=255), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_review_decisions_workflow_id'), 'human_review_decisions', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_review_decisions_workflow_id'), table_name='human_review_decisions')
    op.drop_table('human_review_decisions')
    op.drop_index(op.f('ix_workflow_runs_user_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_session_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_current_status'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mcp_tool_call_audits_tool_name'), table_name='mcp_tool_call_audits')
    op.drop_index(op.f('ix_mcp_tool_call_audits_server_name'), table_name='mcp_tool_call_audits')
    op.drop_index(op.f('ix_mcp_tool_call_audits_correlation_id'), table_name='mcp_tool_call_audits')
    op.drop_table('mcp_tool_call_audits')
    # ### end Alembic commands ###
